name: Create PR for Release Branch

on:
  create:
    branches:
      - '**'
       
jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Version as env var
        run: |
          branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          VERSION=${branch_name#release-}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: ./js/yarn.lock

      - name: Run Lerna version
        working-directory: ./js
        run: npx lerna version v$VERSION --no-git-tag-version --force-publish --tag-version-prefix='' --yes


      - name: Commit changes
        run: |
          git config --local user.email user.email "hello@polybase.xyz"
          git config --local user.name "Polybase CI"
          git add .
          git commit -m "Bump versions" || echo "No changes to commit"
          git push
  
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Release 'v$VERSION'",
              "body": "This is an automated PR for release '$VERSION'",
              "head": "'$branch_name'",
              "base": "main"
            }'
